GlVTKConvert -m /data/surf_extreme3/h_case22.surfmesh -n /data/surf_extreme3/h_case22_Mode1+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode1+3SD            
GlVTKConvert -m /data/surf_extreme3/h_case23.surfmesh -n /data/surf_extreme3/h_case23_Mode1-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode1-3SD  
GlVTKConvert -m /data/surf_extreme3/h_case24.surfmesh -n /data/surf_extreme3/h_case24_Mode2+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode2+3SD  
GlVTKConvert -m /data/surf_extreme3/h_case25.surfmesh -n /data/surf_extreme3/h_case25_Mode2-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode2-3SD  
GlVTKConvert -m /data/surf_extreme3/h_case26.surfmesh -n /data/surf_extreme3/h_case26_Mode3+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode3+3SD  
GlVTKConvert -m /data/surf_extreme3/h_case27.surfmesh -n /data/surf_extreme3/h_case27_Mode3-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode3-3SD  
GlVTKConvert -m /data/surf_extreme3/h_case28.surfmesh -n /data/surf_extreme3/h_case28_Mode4+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode4+3SD  
GlVTKConvert -m /data/surf_extreme3/h_case29.surfmesh -n /data/surf_extreme3/h_case29_Mode4-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode4-3SD  
GlVTKConvert -m /data/surf_extreme3/h_case30.surfmesh -n /data/surf_extreme3/h_case30_Mode5+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode5+3SD  
GlVTKConvert -m /data/surf_extreme3/h_case31.surfmesh -n /data/surf_extreme3/h_case31_Mode5-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode5-3SD  
GlVTKConvert -m /data/surf_extreme3/h_case32.surfmesh -n /data/surf_extreme3/h_case32_Mode6+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode6+3SD  
GlVTKConvert -m /data/surf_extreme3/h_case33.surfmesh -n /data/surf_extreme3/h_case33_Mode6-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode6-3SD  
GlVTKConvert -m /data/surf_extreme3/h_case34.surfmesh -n /data/surf_extreme3/h_case34_Mode7+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode7+3SD  
GlVTKConvert -m /data/surf_extreme3/h_case35.surfmesh -n /data/surf_extreme3/h_case35_Mode7-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode7-3SD  
GlVTKConvert -m /data/surf_extreme3/h_case36.surfmesh -n /data/surf_extreme3/h_case36_Mode8+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode8+3SD  
GlVTKConvert -m /data/surf_extreme3/h_case37.surfmesh -n /data/surf_extreme3/h_case37_Mode8-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode8-3SD  
GlVTKConvert -m /data/surf_extreme3/h_case38.surfmesh -n /data/surf_extreme3/h_case38_Mode9+3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode9+3SD  
GlVTKConvert -m /data/surf_extreme3/h_case39.surfmesh -n /data/surf_extreme3/h_case39_Mode9-3SD.dat -F bin -o /home/crg17/Desktop/transfer/Mode9-3SD  